variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

stages:
  - build

# Build for Ground Station (e.g. RK3566)
build-gs:
  stage: build
  script:
    - echo "▶️ Building for PLATFORM=gs"
    - source /opt/aarch64-buildroot-linux-gnu_sdk-buildroot/environment-setup
    - mkdir -p build-gs
    - cd build-gs
    - cmake -DPLATFORM=gs -DCMAKE_INSTALL_PREFIX=../artifacts/gs -DCMAKE_TOOLCHAIN_FILE=$SDK_PATH/share/buildroot/toolchainfile.cmake ..
    - make j`$(nproc)`
    - make install
    - cd ..
  artifacts:
    paths:
      - artifacts/gs/*
      - build-gs/*
    expire_in: 2 weeks

# Build for Drone (e.g. RV1126)
build-drone:
  stage: build
  script:
    - echo "▶️ Building for PLATFORM=drone"
    - source /opt/vision-sdk/environment-setup
    - mkdir -p build-drone
    - cd build-drone
    - cmake -DPLATFORM=drone -DCMAKE_INSTALL_PREFIX=../artifacts/drone -DCMAKE_TOOLCHAIN_FILE=$SDK_PATH/share/buildroot/toolchainfile.cmake ..
    - make j`$(nproc)`
    - make install
    - cd ..
  artifacts:
    paths:
      - artifacts/drone/*
      - build-drone/*
    expire_in: 2 weeks
