stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage.
  stage: build
  script:
    - echo "Compiling the project ..."
    # SDK and toolchain are prepared in the directory /opt/aarch64-buildroot-linux-gnu_sdk-buildroot
    - source /opt/aarch64-buildroot-linux-gnu_sdk-buildroot/environment-setup
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../artifacts -DCMAKE_TOOLCHAIN_FILE=$SDK_PATH/share/buildroot/toolchainfile.cmake ..
    - make -j24
    - make install
    - echo "Compile complete."
    - cd ..

  artifacts:
    paths:
      - artifacts/bin/*
      - build/*
    expire_in: 2 week
